### PR TITLE
Changes to support different size floppy sizes

### PR DESCRIPTION
**Pull request by Zardoz89**
And a list with a few floppy sizes : 1440KB, 720KB, 360KB and 160KB

### CODE REVIEW

**Comment by paultech** [comment]
This is ready to support in old emulator but isiCPU will need to be updated to conform
@Meisaka Do you want TC-specific hardware changes included in https://github.com/Meisaka/isiCPU or  should we use https://github.com/techcompliant/isiCPU for TC-hardware?

Once that change is in, we can close this

**Comment by sctjkc01** [comment]
@paultech - I might not be Meisaka, but I'd like to weigh in that TC-specific things should probably stay in the TV branch of isiCPU. After all, it wouldn't technically apply to the original Notchian/legacy hardware specs.

**Comment by paultech** [comment]
@Zardoz89 I'm about ready for this. Can you confirm what changes are needed?

Here is the code for the current emulator - https://github.com/techcompliant/isiCPU/blob/master/hardware/floppy_m35.c

**Comment by andyleap** [comment]
@Zardoz89 could we see about updating this PR to match the new directory layout?

**Comment by paultech** [comment]
Superseded by #39

**Pull request closed without merging**
