### PR TITLE
DecaSys EEPROM

### PR DESCRIPTION
**Pull request by andyleap**
Simple EEPROM spec, designed to hold a tiny amount of supplementary data on a device.  Designed to be integrated into devices, rather then used on it's own.

### CODE REVIEW

**Comment by Zardoz89** [comment]
I would : 
- Make bigger. 8 words is ridiculous low. Ever, embed EEPROMS are many times bigger than that. A not embed EEPROM should have capacity of at least 4KiW to have some sense and be usefull.
- Make reading faster -> A pace of one word per 1 or 2 CPU clocks. 
- Making more slow writing on it. Writing on a EEPROM is a slow process  (~8ms per word!) and requires  some extra energy. On a real world EEPROM, usually they have an extra power supply pin (around +12/15 Volts), for writing.
- They have a limited write endurance. Like 100000 cycles per word. I don't know if this would be a good idea from the viewpoint of gameplay.
- I would rename "Clear" instead of "reset", putting the whole EEPROM to0xFFFF

**Comment by andyleap** [comment]
- It's not meant to be an independent device, it's meant to be embedded in other devices.  8 words is what the @paultech himself desired.  It's not supposed to be a storage device.
- As "not a storage device", a slow read time isn't that big a deal
- It's already 5ms a word, but I could bump it.
- That's something to involve @paultech in.
- Clear has connotations of "clearing bits", i.e. setting them to 0, whereas RESET sets them all to 1.

**Comment by paultech** [comment]
@Zardoz89 - As andy stated this EEPROM may be on multiple devices so we wanted to reduce the chance that players would abuse the EEPROM as free memory/storage.  

We may of gone too extreme with 8 words - We can likely bump it up so long as we have enough limitations in place to limit abuse. (Our rule of not adding hardware that overpowers the DCPU)

Write endurance - I like!

**Comment by Zardoz89** [comment]
Oh! I don't read that means to be embed inside other devices. I thought like a independent device. So really, this is more like a standard that devices could follow. Then, it's ok. Also, I read later the true "eeprom cartridge device" (  #12 ), were bigger sizes have sense.

**Comment by paultech** [comment]
@Meisaka @andyleap This one will be interesting with isiCPU - @Meisaka will the new attachment system allow for hardware in hardware? If not I think should have a eeprom.h/.c and macros to add HWI calls into any hardware that has a EEPROM

Thoughts?

**Comment by andyleap** [comment]
I'm personally leaning towards macros as a one solution, though it could possibly be implemented earlier like the way HWQ is automatically handled for static values, and basically just have a "set this to true and you have an EEPROM on this device"

**Comment by paultech** [comment]
> basically just have a "set this to true and you have an EEPROM on this device"

https://github.com/techcompliant/TC-Specs/issues/15 mentions using one of the bits in [device-type](https://github.com/techcompliant/TC-Specs/blob/master/device-type.md). If we get device-type implemented in isisCPU we could use the bit to indicate EEPROM presence and early/late handling of interrupts..

PS. Be aware of circular references.

**Pull request merged**
