### PR TITLE
Added initial version of UPS Specification

### PR DESCRIPTION
**Pull request by orlof**
This change is [Reviewable](https://reviewable.io/reviews/techcompliant/tc-specs/1)

### CODE REVIEW

**Comment by techcompliant** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/techcompliant/tc-specs/1)_

**Comment by orlof** [comment]
I think we can delete this pr. The pps pr replaces this one.

**Comment by paultech** [comment]
Superseded by https://github.com/techcompliant/TC-Specs/pull/3

**Comment by techcompliant** [comment]
Superseded by https://github.com/techcompliant/TC-Specs/pull/3

**Pull request closed without merging**
