### PR TITLE
Update DCPU.md

### PR DESCRIPTION
**Pull request by wolfnether**

### CODE REVIEW

**Comment by paultech** [comment]
It appears to be escaping the `|` correctly when I view the markdown, is there some other issue I'm missing?

**Comment by bshepherdson** [comment]
It's busted in master, look at the `BOR` line [here](https://github.com/techcompliant/TC-Specs/blob/master/CPU/DCPU.md).

**Comment by paultech** [comment]
Sure enough...

**Comment by paultech** [comment]
Thanks for PR and sorry for delay!

**Pull request merged**
